"""
============================================================
LLM Engine — Generates Pandas code from natural language
============================================================
PRIMARY:  Google Gemini 1.5 Flash (free tier, 15 req/min)
FALLBACK: Keyword-matching stub (when no API key is set)

Set GEMINI_API_KEY in your .env to enable real AI.
Get a free key at: https://aistudio.google.com/apikey

IMPORTANT:
  - The LLM ONLY generates code strings
  - It NEVER executes code
  - All output passes through the validation layer
============================================================
"""

import os
import re
from typing import Dict, Any, List

# -- Use the new google.genai SDK (replaces deprecated google.generativeai) --
try:
    from google import genai
    from google.genai import types as genai_types
    _GEMINI_SDK_AVAILABLE = True
except ImportError:
    _GEMINI_SDK_AVAILABLE = False


class LLMEngine:
    """
    LLM integration for natural-language to Pandas code generation.

    Uses Google Gemini 1.5 Flash when GEMINI_API_KEY is set in .env.
    Falls back to keyword-matching stub when no key is available.
    """

    def __init__(self):
        self.api_key = os.getenv("GEMINI_API_KEY", "").strip()
        self.use_gemini = _GEMINI_SDK_AVAILABLE and bool(self.api_key)
        self.is_stub = not self.use_gemini

        if self.use_gemini:
            self.client = genai.Client(api_key=self.api_key)
            print("[LLMEngine] Gemini 1.5 Flash loaded -- real AI active")
        else:
            self.client = None
            if not _GEMINI_SDK_AVAILABLE:
                print("[LLMEngine] google-genai not installed -- using stub")
            else:
                print("[LLMEngine] GEMINI_API_KEY not set -- using stub fallback")

    # ---------------------------------------------------------
    # Public API
    # ---------------------------------------------------------

    def generate_code(self, natural_query: str, schema_summary: str) -> Dict[str, Any]:
        """
        Convert a natural language query into Pandas code.

        Parameters:
            natural_query: The user question
            schema_summary: Schema context string from schema_extractor

        Returns:
            {
                "code": str,         # Generated Pandas code
                "confidence": float, # 0.0-1.0
                "explanation": str,  # Human-readable explanation
                "engine": str        # "gemini-1.5-flash" or "keyword-stub"
            }
        """
        if self.use_gemini:
            return self._gemini_generate(natural_query, schema_summary)
        return self._stub_generate(natural_query, schema_summary)

    # ---------------------------------------------------------
    # Gemini Path (Real AI)
    # ---------------------------------------------------------

    def _gemini_generate(self, natural_query: str, schema_summary: str) -> Dict[str, Any]:
        """
        Call Google Gemini 1.5 Flash to generate Pandas code.
        Falls back to stub if the API call fails.
        """
        from llm.prompt_templates import build_analysis_prompt

        prompt = build_analysis_prompt(natural_query, schema_summary)

        try:
            response = self.client.models.generate_content(
                model="gemini-1.5-flash",
                contents=prompt,
                config=genai_types.GenerateContentConfig(
                    temperature=0.1,
                    max_output_tokens=256,
                    top_p=0.9,
                ),
            )

            raw = response.text.strip()

            # Strip markdown code fences if Gemini wraps in ```python ... ```
            raw = re.sub(r"^```(?:python)?\n?", "", raw)
            raw = re.sub(r"\n?```$", "", raw)
            code = raw.strip()

            # Basic sanity check -- must reference df
            if not code or "df" not in code:
                raise ValueError(f"Gemini returned invalid code: {repr(code)}")

            return {
                "code": code,
                "confidence": 0.92,
                "explanation": f"Generated by Gemini AI for: {natural_query!r}",
                "engine": "gemini-1.5-flash",
            }

        except Exception as e:
            print(f"[LLMEngine] Gemini error: {e} -- falling back to stub")
            result = self._stub_generate(natural_query, schema_summary)
            result["explanation"] = f"Gemini unavailable, used fallback. ({e})"
            result["engine"] = "stub-fallback"
            return result

    # ---------------------------------------------------------
    # Stub / Fallback Path (Keyword Matching)
    # ---------------------------------------------------------

    def _stub_generate(self, query: str, schema: str) -> Dict[str, Any]:
        """
        Fallback: keyword matching + schema-aware column extraction.
        Active only when GEMINI_API_KEY is not set.
        """
        query_lower = query.lower().strip()

        columns = self._extract_columns_from_schema(schema)
        numeric_cols = columns.get("numeric", [])
        categorical_cols = columns.get("categorical", [])
        datetime_cols = columns.get("datetime", [])

        mentioned_numeric = self._find_mentioned_column(query_lower, numeric_cols)
        mentioned_categorical = self._find_mentioned_column(query_lower, categorical_cols)

        default_num = numeric_cols[0] if numeric_cols else None
        default_cat = categorical_cols[0] if categorical_cols else None

        num = mentioned_numeric or default_num
        cat = mentioned_categorical or default_cat

        code = None
        explanation = None

        if any(kw in query_lower for kw in ["average", "mean", "avg"]):
            if any(kw in query_lower for kw in ["by", "per", "each", "group"]) and cat and num:
                code = f"df.groupby('{cat}')['{num}'].mean().reset_index()"
                explanation = f"Average of '{num}' grouped by '{cat}'"
            elif num:
                code = f"df['{num}'].mean()"
                explanation = f"Overall average of '{num}'"
            else:
                code = "df.describe()"
                explanation = "Descriptive statistics"

        elif any(kw in query_lower for kw in ["sum", "total"]):
            if any(kw in query_lower for kw in ["by", "per", "each", "group"]) and cat and num:
                code = f"df.groupby('{cat}')['{num}'].sum().reset_index()"
                explanation = f"Total '{num}' by '{cat}'"
            elif num:
                code = f"df['{num}'].sum()"
                explanation = f"Sum of '{num}'"
            else:
                code = "df.describe()"
                explanation = "Descriptive statistics"

        elif any(kw in query_lower for kw in ["count", "how many"]):
            if cat:
                code = f"df['{cat}'].value_counts().reset_index()"
                explanation = f"Count of each '{cat}'"
            else:
                code = "df.shape[0]"
                explanation = "Total row count"

        elif any(kw in query_lower for kw in ["max", "maximum", "highest", "top", "largest", "best"]):
            if cat and num:
                code = f"df.groupby('{cat}')['{num}'].max().reset_index().nlargest(10, '{num}')"
                explanation = f"Max '{num}' by '{cat}'"
            elif num:
                code = f"df.nlargest(10, '{num}')"
                explanation = f"Top 10 rows by '{num}'"
            else:
                code = "df.head(10)"
                explanation = "Top 10 rows"

        elif any(kw in query_lower for kw in ["min", "minimum", "lowest", "bottom", "smallest", "worst"]):
            if cat and num:
                code = f"df.groupby('{cat}')['{num}'].min().reset_index().nsmallest(10, '{num}')"
                explanation = f"Min '{num}' by '{cat}'"
            elif num:
                code = f"df.nsmallest(10, '{num}')"
                explanation = f"Bottom 10 rows by '{num}'"
            else:
                code = "df.head(10)"
                explanation = "Bottom rows"

        elif any(kw in query_lower for kw in ["describe", "summary", "statistics", "stats", "overview"]):
            code = "df.describe()"
            explanation = "Descriptive statistics for all numeric columns"

        elif any(kw in query_lower for kw in ["distribution", "spread", "breakdown"]):
            if cat:
                code = f"df['{cat}'].value_counts().reset_index()"
                explanation = f"Distribution of '{cat}'"
            elif num:
                code = f"df['{num}'].describe()"
                explanation = f"Distribution of '{num}'"
            else:
                code = "df.describe()"
                explanation = "Distribution of all columns"

        elif any(kw in query_lower for kw in ["correlation", "correlate", "relationship"]):
            code = "df.corr(numeric_only=True)"
            explanation = "Correlation matrix"

        elif any(kw in query_lower for kw in ["trend", "over time", "timeline", "time series"]):
            if datetime_cols and num:
                dt = datetime_cols[0]
                code = f"df.groupby('{dt}')['{num}'].mean().reset_index()"
                explanation = f"Trend of '{num}' over '{dt}'"
            elif num and cat:
                code = f"df.groupby('{cat}')['{num}'].mean().reset_index()"
                explanation = f"'{num}' across '{cat}'"
            else:
                code = "df.head(20)"
                explanation = "Dataset preview"

        elif any(kw in query_lower for kw in ["compare", "comparison", "versus", "vs"]):
            if cat and num:
                code = f"df.groupby('{cat}')['{num}'].mean().reset_index()"
                explanation = f"Comparison of '{num}' across '{cat}'"
            else:
                code = "df.describe()"
                explanation = "Comparison statistics"

        elif any(kw in query_lower for kw in ["unique", "distinct"]):
            if cat:
                code = f"df['{cat}'].unique().tolist()"
                explanation = f"Unique values in '{cat}'"
            else:
                code = "df.nunique()"
                explanation = "Unique count per column"

        elif any(kw in query_lower for kw in ["missing", "null", "empty", "na"]):
            code = "df.isnull().sum().reset_index()"
            explanation = "Missing value count per column"

        elif any(kw in query_lower for kw in ["show", "display", "list", "view", "see", "give"]):
            if any(kw in query_lower for kw in ["all", "everything", "full"]):
                code = "df.head(50)"
                explanation = "First 50 rows"
            elif cat and num:
                code = f"df.groupby('{cat}')['{num}'].mean().reset_index()"
                explanation = f"'{num}' by '{cat}'"
            else:
                code = "df.head(20)"
                explanation = "First 20 rows"

        else:
            if mentioned_numeric and mentioned_categorical:
                code = f"df.groupby('{mentioned_categorical}')['{mentioned_numeric}'].mean().reset_index()"
                explanation = f"Average '{mentioned_numeric}' by '{mentioned_categorical}'"
            elif mentioned_categorical:
                code = f"df['{mentioned_categorical}'].value_counts().reset_index()"
                explanation = f"Distribution of '{mentioned_categorical}'"
            elif mentioned_numeric:
                code = f"df['{mentioned_numeric}'].describe()"
                explanation = f"Statistics for '{mentioned_numeric}'"
            else:
                code = "df.head(10)"
                explanation = "Dataset preview"

        return {
            "code": code,
            "confidence": 0.75,
            "explanation": explanation,
            "engine": "keyword-stub",
        }

    # ---------------------------------------------------------
    # Helpers
    # ---------------------------------------------------------

    def _find_mentioned_column(self, query: str, column_list: List[str]) -> str:
        if not column_list:
            return None
        sorted_cols = sorted(column_list, key=len, reverse=True)
        for col in sorted_cols:
            col_lower = col.lower()
            col_space = col_lower.replace("_", " ")
            if col_lower in query or col_space in query:
                return col
        return None

    def _extract_columns_from_schema(self, schema: str) -> Dict[str, list]:
        columns = {"numeric": [], "categorical": [], "datetime": [], "boolean": []}
        for line in schema.split("\n"):
            line = line.strip()
            if not line.startswith("- "):
                continue
            content = line[2:]
            paren_idx = content.find("(")
            if paren_idx == -1:
                continue
            col_name = content[:paren_idx].strip()
            rest = content[paren_idx + 1:]
            close_paren = rest.find(")")
            if close_paren == -1:
                continue
            col_type = rest[:close_paren].strip().lower()
            if col_type in columns:
                columns[col_type].append(col_name)
        return columns


# -- Module-level singleton --
llm_engine = LLMEngine()
